language: c

addons:
  apt:
    packages:
    - liblzma-dev

matrix:
  include:
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
  - os: linux
    compiler: gcc
    env: CFLAGS="-std=gnu99 -O0"
  - os: osx
    compiler: gcc

env:
  global:
  - HTSLIB=`pwd`/htslib
  - HTSDIR=$HTSLIB/b
  - SAMTOOLSDIR=`pwd`/samtools
  - PATH=$SAMTOOLSDIR:$PATH
  - DISTCHECK_CONFIGURE_FLAGS=--with-htslib=$HTSDIR

install:
- .travis/clone ${HTSREPO:-git://github.com/samtools/htslib.git} $HTSLIB master
- .travis/clone ${HTSREPO:-git://github.com/samtools/samtools.git} $SAMTOOLSDIR master

before_script:
- (cd $HTSLIB && autoreconf && mkdir b && ./configure --prefix=$HTSDIR && make && make install)
- (cd $SAMTOOLSDIR && autoconf && make)

script: autoreconf -i && ./configure -V && ./configure --with-htslib=$HTSDIR && make distcheck

after_success:
  - make dist
  - export DIST_FILE=$(ls bambi-*.tar.gz)
  - export SHA256_FILE=$DIST_FILE.sha256
  - shasum -a 256 $DIST_FILE > $SHA256_FILE

deploy:
  provider: releases
  api_key:
    secure: ThARbt8qf7uZsgT/2Di49LOeeUI5NKUP7OKm8WIG2POrjHoxMBFn6xwirRfDLdIGWc93WUjK99y5o0PcHzkvgsqBKMsmBdb3Gar34Wn35Xc7rW/kChv95cXKWAVT12I212Qltiq0M8Ge8tLTou3P5IF/gKZD/aCvTCR+HkZP6WNS63zM+0RxFptw9BUqlPSfBHRJmk6zPLBkxSrq126Um3FEDEr33lU7uOvEiY69gnpQBVNBNS+g4fD/6Trvdj8x3s/IqnnGp4b4Vmz11nK9bkKOavVzFYplq0z//7fpOhhsCppD1pNhyUX9JHZ+/hEkZ1pGzx2QHIHrp23e54CRiWKEFBZ88LJOH7Hjiht7HfdaMUVwF+j8yWD3+3VIhspCk04un9uIFoG0x6IJ1kfzLpvpYuxhdnvCZymfMbsRkvx9vOyeLARZXiw8+UEYDJNxPqho1tJoQtrW5f0CkpQFkSw5qn/VYdotyuVw8fkpK1g/zjzWKS+2Av2XLTFf67ULZeArdaAZqxXI5vnKg3YkJDdkQ8/eiXTYhKkjTP8bx4RXbcdXDTGUPXJBNd6wm4h+KMsa9+Yht1iU3xuALCV3wi8KdNRPA3IDrCH0aXxI5hulqR+iPkMPXsbyhh/TyENkNuB6TgSSNpkeH9Y6kCuODEywT2D5CEEaZMADt+jEINs=
  file:
    - $DIST_FILE
    - $SHA256_FILE
  skip_cleanup: true
  on:
    tags: true
    repo: jenniferliddle/bambi
    branch: master
